# Generated by Django 4.2 on 2023-05-05 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeBranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=256)),
                ('branch_label', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassDivisionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=4)),
                ('medium', models.IntegerField(choices=[(0, 'NA'), (1, 'English Medium'), (2, 'Malayalam Medium')], default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch_class.officebranchmodel')),
            ],
            options={
                'unique_together': {('branch', 'standard', 'division')},
            },
        ),
    ]
