# Generated by Django 4.2 on 2023-05-21 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch_class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('admission_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('student_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10)),
                ('parent_name', models.CharField(max_length=200)),
                ('student_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch_class.classdivisionmodel')),
            ],
        ),
    ]
