# Generated by Django 4.2 on 2023-05-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='admission_number',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
