# Generated by Django 4.2 on 2023-05-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_students_admission_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='admission_number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
