# Generated by Django 4.2 on 2023-05-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0002_feemonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='month',
            field=models.CharField(default=5, max_length=20),
        ),
    ]
