# Generated by Django 4.2 on 2023-05-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_students_is_absent_alter_students_admission_number'),
        ('fee', '0003_fees_month'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fees',
            unique_together={('student', 'month')},
        ),
    ]
