# Generated by Django 4.2 on 2023-05-23 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch_class', '0001_initial'),
        ('attendance', '0003_holiday_branch_alter_holiday_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch_class.officebranchmodel'),
        ),
    ]
